- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: go mod initalization
  ansible.builtin.shell: go mod init dispatch; go get; go build
  args:
     chdir: /app

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml