- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install a list of packages (suitable replacement for 2.11 loop deprecation warning)
  ansible.builtin.yum:
    name:
      - nginx
      - postgresql
      - postgresql-server
    state: present

